<?php

namespace Pcd\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EntryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GuestbookRepository extends EntityRepository
{
    public function getEntries()
    {
      $query = $this->createQueryBuilder('a')
                    ->orderBy('a.createAt', 'DESC')
                    ->getQuery();

      return $query->getResult();
    }
}

?>