# app/config/parameters.yml

parameters:
    database_driver:   pdo_mysql
    database_host:     127.0.0.1
    database_port:     ~
    database_name:     PcDirect
    database_user:     root
    database_password: ~

    mailer_transport:  gmail
    mailer_encryption: ssl
    mailer_auth_mode: Connexion
    mailer_host: jonath.xiong@gmail.com
    mailer_user: jonath.xiong
    mailer_password: Chivl2ej

    locale:            fr
    secret:            ThisTokenIsNotSoSecretChangeIt
