# app/config/routing.yml
pcd_blog:
    resource: "@PcdBlogBundle/Resources/config/routing.yml"
    prefix:   /

# Routes Identification
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
 
fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile
 
fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register
 
fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting
 
fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
    
# Routes Captcha
gregwar_captcha_routing:
    resource: "@GregwarCaptchaBundle/Resources/config/routing/routing.yml"
    prefix: /_gcb

# Routes Sylius
sylius_product:
    resource: "@SyliusProductBundle/Resources/config/routing.yml"

#sylius_cart:
    #resource: "@SyliusCartBundle/Resources/config/routing.yml"
    #prefix: /cart