parameters:
#    pcd_blog.example.class: Pcd\BlogBundle\Example

services:
#    pcd_blog.example:
#        class: %pcd_blog.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
