# src/Pcd/UserBundle/Resources/config/services.yml

parameters:
#    pcd_user.example.class: Pcd\UserBundle\Example

services:
#    pcd_user.example:
#        class: %pcd_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    pcd_user.profile.form.type:
        class: Pcd\UserBundle\Form\Type\ProfileFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: pcd_user_profile }
    pcd_user.registration.form.type:
        class: Pcd\UserBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: pcd_user_registration }
